apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- instances/r660
- instances/r770
- instances/r7725
- instances/xe9712
- instances/gpu-dpu
- instances/basic
- instances/r660-go
- instances/r770-go
- instances/r7725-go
- instances/xe9712-go
- instances/gpu-dpu-go
- instances/basic-go
