apiVersion: apps/v1
kind: Deployment
metadata:
  name: metalprobe-mock-controller
  labels:
    app.kubernetes.io/name: metalprobe-mock-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metalprobe-mock-controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: metalprobe-mock-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: metalprobe-mock-controller:latest
        imagePullPolicy: IfNotPresent
        command:
        - /metalprobe-mock-controller
        args:
        - --leader-elect
        ports:
        - containerPort: 8081
          name: health
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: metalprobe-mock-controller
      terminationGracePeriodSeconds: 10
