apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metal-operator-system

resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml

images:
- name: metalprobe-mock-controller
  newName: metalprobe-mock-controller
  newTag: latest
