# Instance overlay for the XE9712 iDRAC Go mockup client.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metal-operator-system

components:
- ../../components/go-mockup

namePrefix: redfish-xe9712-go-

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: xe9712-go

patches:
- target:
    kind: Service
    name: mockup
  patch: |-
    - op: replace
      path: /spec/clusterIP
      value: 10.96.200.23
- target:
    kind: Deployment
    name: mockup
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/3
      value: /clients/XE9712_iDRAC10_1_30_07_10_mockup_client/redfish/v1
    - op: replace
      path: /spec/template/spec/volumes/0/hostPath/path
      value: /redfish-clients
- target:
    kind: BMC
    name: mockup
  patch: |-
    - op: replace
      path: /spec/bmcSecretRef/name
      value: redfish-xe9712-go-mockup
    - op: replace
      path: /spec/hostname
      value: dell-xe9712-go-mockup
    - op: replace
      path: /spec/access/ip
      value: 10.96.200.23
- target:
    kind: BMCSecret
    name: mockup
  patch: |-
    - op: replace
      path: /stringData/username
      value: foo
    - op: replace
      path: /stringData/password
      value: bar
