#!/usr/bin/env bash
# Generate dnsmasq.conf with static leases matching qemu-bmc guest MACs.
# MAC algorithm mirrors qemu-bmc/docker/setup-network.sh generate_mac().
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-${ROOT}/config/dnsmasq.conf}"

# Fixed SYSTEM_UUID values must match infra.clab.yaml workers.
NODE1_UUID="11111111-1111-1111-1111-111111111111"
NODE2_UUID="22222222-2222-2222-2222-222222222222"

generate_mac() {
  local uuid="$1"
  local ifname="$2"
  local hash
  hash=$(echo -n "${uuid}:${ifname}" | md5sum | cut -c1-6)
  echo "52:54:00:${hash:0:2}:${hash:2:2}:${hash:4:2}"
}

# eth1 = OOB/iDRAC, eth2 = IB/NIC1 (VM_NETWORKS in topology)
NODE1_OOB_MAC=$(generate_mac "${NODE1_UUID}" eth1)
NODE1_IB_MAC=$(generate_mac "${NODE1_UUID}" eth2)
NODE2_OOB_MAC=$(generate_mac "${NODE2_UUID}" eth1)
NODE2_IB_MAC=$(generate_mac "${NODE2_UUID}" eth2)

mkdir -p "$(dirname "${OUT}")"

cat >"${OUT}" <<EOF
# Generated by scripts/gen-dhcp-leases.sh — do not edit by hand.
# DHCP only (no DNS); interfaces are plain eth1/eth2 on the dnsmasq node.
port=0
interface=eth1
interface=eth2
bind-interfaces
except-interface=lo

dhcp-range=set:oob,172.16.100.0,static
dhcp-range=set:ib,10.250.200.0,static

dhcp-host=${NODE1_OOB_MAC},172.16.100.11,node1-idrac,infinite
dhcp-host=${NODE1_IB_MAC},10.250.200.11,node1-nic1,infinite
dhcp-host=${NODE2_OOB_MAC},172.16.100.12,node2-idrac,infinite
dhcp-host=${NODE2_IB_MAC},10.250.200.12,node2-nic1,infinite

dhcp-option=tag:oob,option:router,172.16.100.1
dhcp-option=tag:ib,option:router,10.250.200.1
EOF

echo "Wrote ${OUT}"
echo "  node1 OOB ${NODE1_OOB_MAC} -> 172.16.100.11"
echo "  node1 IB  ${NODE1_IB_MAC} -> 10.250.200.11"
echo "  node2 OOB ${NODE2_OOB_MAC} -> 172.16.100.12"
echo "  node2 IB  ${NODE2_IB_MAC} -> 10.250.200.12"
