#!/usr/bin/env bash
# Generate FeDHCP's static MAC->IP leases file matching qemu-bmc guest MACs.
# MAC algorithm is taken from qemu-bmc/docker/setup-network.sh generate_mac().
#
# OOB BMC addresses are static on the qemu-bmc containers' eth1 and are not
# leased. Only guest IB NICs (VM_NETWORKS=eth2) use DHCP.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-${ROOT}/../../config/fedhcp/leases_v4.txt}"

# Fixed SYSTEM_UUID values must match infra.clab.yaml workers.
NODE1_UUID="11111111-1111-1111-1111-111111111111"
NODE2_UUID="22222222-2222-2222-2222-222222222222"

generate_mac() {
  local uuid="$1"
  local ifname="$2"
  local hash
  hash=$(echo -n "${uuid}:${ifname}" | md5sum | cut -c1-6)
  echo "52:54:00:${hash:0:2}:${hash:2:2}:${hash:4:2}"
}

# Guest IB NIC is container eth2 (VM_NETWORKS).
NODE1_IB_MAC=$(generate_mac "${NODE1_UUID}" eth2)
NODE2_IB_MAC=$(generate_mac "${NODE2_UUID}" eth2)

mkdir -p "$(dirname "${OUT}")"

cat >"${OUT}" <<EOF
# Generated by scripts/gen-dhcp-leases.sh — do not edit by hand.
# Static MAC -> IPv4 leases for FeDHCP's "file" plugin, IB bus only.
${NODE1_IB_MAC} 10.250.200.11
${NODE2_IB_MAC} 10.250.200.12
EOF

echo "Wrote ${OUT}"
echo "  node1 IB ${NODE1_IB_MAC} -> 10.250.200.11"
echo "  node2 IB ${NODE2_IB_MAC} -> 10.250.200.12"
