bmcIP: "10.96.200.25"
bmcPort: 8000
bmcScheme: http
username: foo
password: bar
model: "15G Monolithic"
firmwareVersion: "7.10.30.00"
powerState: "On"
image: "ghcr.io/ironcore-dev/gardenlinux:2150.4.0-metal-amd64"
