apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/ironcore-dev/metal-operator//config/default?ref=35a86bac04c01208a3fb6593b498388590d05f5b
- registry_service.yaml
- macdb-secret.yaml

configMapGenerator:
- name: ignition-template
  namespace: metal-operator-system
  files:
  - ignition-template.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
- path: manager_patch.yaml
- path: metaldata_patch.yaml

images:
- name: controller
  newName: controller
  newTag: latest
- name: metaldata
  newName: metaldata
  newTag: latest
