apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../metal-operator/config/default
- registry_service.yaml
- macdb-secret.yaml

patches:
- path: manager_patch.yaml
- path: metaldata_patch.yaml

images:
- name: controller
  newName: controller
  newTag: latest
- name: metaldata
  newName: metaldata
  newTag: latest
