apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect
        - --metrics-bind-address=:8443
        - --health-probe-bind-address=:8081
        - --mac-prefixes-file=/etc/macdb/mac_prefixes.yaml
        - --probe-image=ghcr.io/ironcore-dev/metalprobe:latest
        - --probe-os-image=ghcr.io/ironcore-dev/gardenlinux:2150.4.0-metal
        - --registry-url=http://metal-registry.metal-operator-system.svc:30000
        - --registry-port=30000
        - --skip-cert-validation
        ports:
        - containerPort: 8081
          name: health
          protocol: TCP
        - containerPort: 30000
        volumeMounts:
        - mountPath: /etc/macdb/
          name: macdb
      volumes:
      - name: macdb
        secret:
          defaultMode: 420
          secretName: macdb
