registry:
  enabled: true
  port: 30000

prometheus:
  enable: false

controllerManager:
  manager:
    args:
      - "--leader-elect"
      - "--metrics-bind-address=:8443"
      - "--health-probe-bind-address=:8081"
      - "--probe-image=ghcr.io/ironcore-dev/metalprobe:latest"
      - "--probe-os-image=ghcr.io/ironcore-dev/os-images/gardenlinux:1877.0"
      - "--registry-url=http://metal-registry.metal-operator-system.svc:30000"
