apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/ironcore-dev/boot-operator//config/default?ref=8cb11a7785cc02a7acbbf1be6d0228b0dab96a3d
- service.yaml

patches:
- path: manager_patch.yaml

images:
- name: controller
  newName: boot-controller
  newTag: latest
