apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: IfNotPresent
        args:
        - --metrics-bind-address=:8443
        - --leader-elect
        - --metrics-cert-path=/tmp/k8s-metrics-server/metrics-certs
        - --controllers=serverbootconfighttp,httpbootconfig,serverbootconfigpxe,ipxebootconfig
        - --image-server-url=http://10.250.200.2:30083/httpboot
        - --ipxe-service-url=http://10.250.200.2:30082
        - --default-httpboot-oci-image=ghcr.io/ironcore-dev/gardenlinux:2150.4.0-metal
        ports:
        - containerPort: 8081
          name: health
          protocol: TCP
        - containerPort: 8082
          name: ipxe
          protocol: TCP
        - containerPort: 8083
          name: image-proxy
          protocol: TCP
