apiVersion: v1
kind: Service
metadata:
  name: boot-registry
  namespace: boot-operator-system
spec:
  type: NodePort
  ports:
    - name: ipxe
      port: 8082
      targetPort: 8082
      nodePort: 30082
    - name: image-proxy
      port: 8083
      targetPort: 8083
      nodePort: 30083
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: boot-operator
