apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml

configMapGenerator:
- name: fedhcp-config
  namespace: fedhcp-system
  files:
  - config.yaml
  - httpboot_config.yaml
  - leases_v4.txt

images:
- name: fedhcp
  newName: fedhcp
  newTag: latest
