apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSecret
metadata:
  name: mockup
  labels:
    app.kubernetes.io/name: redfish-go-mockup
    app.kubernetes.io/component: redfish-go-mockup
stringData:
  username: PLACEHOLDER_USERNAME
  password: PLACEHOLDER_PASSWORD
