apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yaml
- service.yaml
- bmc.yaml
- bmcsecret.yaml

images:
- name: mock-server
  newName: mock-server
  newTag: latest
