apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../config/metal-operator

configMapGenerator:
- name: ignition-template
  namespace: metal-operator-system
  behavior: replace
  files:
  - ignition-template.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    kind: Deployment
    name: controller-manager
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/6
      value: --registry-url=http://10.250.200.2:30000
    - op: replace
      path: /spec/template/spec/containers/0/args/5
      value: --probe-os-image=ghcr.io/simontesar/metal-operator-test-framework:dev
