apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../config/boot-operator

patches:
- target:
    kind: Deployment
    name: controller-manager
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/3
      value: --controllers=serverbootconfigpxe,ipxebootconfig

images:
- name: boot-controller
  newName: ghcr.io/ironcore-dev/boot-operator
  newTag: sha-8cb11a7
